services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - 8080:80
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - 8000:8000

    volumes:
      - ./backend:/app
    depends_on:
      - frontend
